# Generated by Django 3.2 on 2020-11-18 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminario2app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detallePedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
