# Generated by Django 3.2 on 2020-11-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminario2app', '0002_auto_20201118_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='Cproducto',
            field=models.CharField(max_length=50),
        ),
    ]
