# Generated by Django 3.2 on 2020-11-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminario2app', '0003_auto_20201118_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AlterField(
            model_name='stock',
            name='Cproducto',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
