# Generated by Django 3.2 on 2020-11-18 19:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminario2app', '0004_auto_20201118_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('Cpedido', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Ccliente', models.CharField(max_length=50)),
                ('FechaPedido', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='detallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
                ('Cpedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminario2app.pedido')),
                ('Cproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminario2app.stock')),
            ],
        ),
    ]
