# Generated by Django 3.2 on 2020-12-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminario2app', '0005_detallepedido_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='Ccliente',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='Cpedido',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Cproducto',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
