# Generated by Django 3.2 on 2020-12-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminario2app', '0006_auto_20201201_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='Cpedido',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
